# Generated by Django 4.2.7 on 2025-04-17 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core_components", "0002_alter_fingerprint_id_alter_fingerprintpool_id"),
        ("badelf", "0006_rename_charges_badelf_atom_charges_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ElfAnalysis",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_index=True, null=True),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_index=True, null=True),
                ),
                ("source", models.JSONField(blank=True, null=True)),
                ("structure", models.TextField(blank=True, null=True)),
                ("nsites", models.IntegerField(blank=True, null=True)),
                ("nelements", models.IntegerField(blank=True, null=True)),
                ("elements", models.JSONField(blank=True, null=True)),
                (
                    "chemical_system",
                    models.CharField(blank=True, max_length=25, null=True),
                ),
                ("density", models.FloatField(blank=True, null=True)),
                ("density_atomic", models.FloatField(blank=True, null=True)),
                ("volume", models.FloatField(blank=True, null=True)),
                ("volume_molar", models.FloatField(blank=True, null=True)),
                (
                    "formula_full",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "formula_reduced",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "formula_anonymous",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("total_time", models.FloatField(blank=True, null=True)),
                ("queue_time", models.FloatField(blank=True, null=True)),
                (
                    "workflow_name",
                    models.CharField(blank=True, max_length=75, null=True),
                ),
                (
                    "workflow_version",
                    models.CharField(blank=True, max_length=75, null=True),
                ),
                (
                    "computer_system",
                    models.CharField(blank=True, max_length=75, null=True),
                ),
                ("directory", models.CharField(blank=True, max_length=250, null=True)),
                (
                    "run_id",
                    models.CharField(blank=True, max_length=50, null=True, unique=True),
                ),
                ("corrections", models.JSONField(blank=True, null=True)),
                ("separate_spin", models.BooleanField(blank=True, null=True)),
                ("spin_polarized", models.BooleanField(blank=True, null=True)),
                (
                    "ignore_low_pseuodopotentials",
                    models.BooleanField(blank=True, null=True),
                ),
                ("downscale_resolution", models.FloatField(blank=True, null=True)),
                ("resolution", models.FloatField(blank=True, null=True)),
                ("metal_depth_cutoff", models.FloatField(blank=True, null=True)),
                ("min_covalent_angle", models.FloatField(blank=True, null=True)),
                ("min_covalent_bond_ratio", models.FloatField(blank=True, null=True)),
                ("shell_depth", models.FloatField(blank=True, null=True)),
                ("electride_elf_min", models.FloatField(blank=True, null=True)),
                ("electride_depth_min", models.FloatField(blank=True, null=True)),
                ("electride_charge_min", models.FloatField(blank=True, null=True)),
                ("electride_volume_min", models.FloatField(blank=True, null=True)),
                ("electride_radius_min", models.FloatField(blank=True, null=True)),
                (
                    "radius_refine_method",
                    models.CharField(blank=True, max_length=75, null=True),
                ),
                ("bifurcation_graph_up", models.JSONField(blank=True, null=True)),
                ("bifurcation_graph_down", models.JSONField(blank=True, null=True)),
                ("labeled_structure_up", models.JSONField(blank=True, null=True)),
                ("labeled_structure_down", models.JSONField(blank=True, null=True)),
                (
                    "spacegroup",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core_components.spacegroup",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ElfFeatures",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_index=True, null=True),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_index=True, null=True),
                ),
                ("source", models.JSONField(blank=True, null=True)),
                ("spin", models.CharField(blank=True, max_length=75, null=True)),
                ("basin_type", models.CharField(blank=True, max_length=75, null=True)),
                (
                    "basin_subtype",
                    models.CharField(blank=True, max_length=75, null=True),
                ),
                ("reducible", models.JSONField(blank=True, null=True)),
                ("basins", models.JSONField(blank=True, null=True)),
                ("frac_coords", models.JSONField(blank=True, null=True)),
                ("max_elf", models.FloatField(blank=True, null=True)),
                ("depth", models.FloatField(blank=True, null=True)),
                ("depth_3d", models.FloatField(blank=True, null=True)),
                ("charge", models.FloatField(blank=True, null=True)),
                ("volume", models.FloatField(blank=True, null=True)),
                ("nearest_atom", models.FloatField(blank=True, null=True)),
                (
                    "nearest_atom_type",
                    models.CharField(blank=True, max_length=75, null=True),
                ),
                ("atom_distance", models.FloatField(blank=True, null=True)),
                ("dist_minus_radius", models.FloatField(blank=True, null=True)),
                ("bare_electron_indicator", models.FloatField(blank=True, null=True)),
                ("bare_electron_scores", models.JSONField(blank=True, null=True)),
                ("coord_number", models.IntegerField(blank=True, null=True)),
                ("coord_atom_indices", models.JSONField(blank=True, null=True)),
                ("coord_atom_types", models.JSONField(blank=True, null=True)),
                (
                    "elf_analysis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="elf_features",
                        to="badelf.elfanalysis",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
