# Generated by Django 4.2.7 on 2025-04-24 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("badelf", "0007_elfanalysis_elffeatures"),
    ]

    operations = [
        migrations.RenameField(
            model_name="elffeatures",
            old_name="dist_minus_radius",
            new_name="feature_radius",
        ),
        migrations.RemoveField(
            model_name="elfanalysis",
            name="metal_depth_cutoff",
        ),
        migrations.AddField(
            model_name="elfanalysis",
            name="min_covalent_charge",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
