# Generated by Django 4.2.7 on 2025-05-06 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("badelf", "0008_rename_dist_minus_radius_elffeatures_feature_radius_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="elfanalysis",
            name="resolution",
        ),
        migrations.AddField(
            model_name="elffeatures",
            name="dist_beyond_atom",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
