# Generated by Django 4.2.7 on 2025-05-07 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("badelf", "0009_remove_elfanalysis_resolution_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="elffeatures",
            name="feature_structure_index",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
